# Generated by Django 5.2.17 on 2026-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('authority', models.CharField(max_length=255)),
                ('level', models.JSONField(default=list)),
                ('income_ceiling_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('age_limit_years', models.IntegerField(blank=True, null=True)),
                ('age_limit_by_course', models.JSONField(blank=True, null=True)),
                ('min_marks_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_marks_percent_pg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('study_destination', models.CharField(default='India', max_length=100)),
                ('requires', models.JSONField(blank=True, default=list)),
                ('excludes_if', models.JSONField(blank=True, default=list)),
                ('other_conditions', models.JSONField(blank=True, default=list)),
                ('fields_of_study', models.JSONField(blank=True, default=list)),
                ('benefit_summary', models.TextField()),
                ('indicative_annual_benefit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-indicative_annual_benefit', 'name'],
            },
        ),
    ]
